package io.bashpsk.zerodownload.domain.settings

@Suppress("SpellCheckingInspection", "unused")
enum class AppLanguage(val code: String, val language: String) {

    System(code = "", language = "System"),
    Tamil(code = "ta", language = "தமிழ்"),
    English(code = "en", language = "English"),
    EnglishIndia(code = "en-IN", language = "English (India)"),
    EnglishUK(code = "en-GB", language = "English (UK)"),
    EnglishUS(code = "en-US", language = "English (US)"),
//    Afrikaans(code = "af", language = "Afrikaans"),
//    Aghem(code = "agq", language = "Aghem"),
//    Akan(code = "ak", language = "Akan"),
//    Albanian(code = "sq", language = "shqip"),
//    Amharic(code = "am", language = "አማርኛ"),
//    Arabic(code = "ar", language = "العربية"),
//    Armenian(code = "hy", language = "հայերեն"),
//    Assamese(code = "as", language = "অসমীয়া"),
//    Asturian(code = "ast", language = "asturianu"),
//    Asu(code = "asa", language = "Kipare"),
//    Azerbaijani(code = "az", language = "azərbaycan"),
//    Bafia(code = "ksf", language = "rikpa"),
//    Bambara(code = "bm", language = "bamanakan"),
//    Basaa(code = "bas", language = "Ɓàsàa"),
//    Basque(code = "eu", language = "euskara"),
//    Belarusian(code = "be", language = "беларуская"),
//    Bemba(code = "bem", language = "Ichibemba"),
//    Bena(code = "bez", language = "Hibena"),
//    Bengali(code = "bn", language = "বাংলা"),
//    Bhojpuri(code = "bho", language = "भोजपुरी"),
//    Bodo(code = "brx", language = "बर’"),
//    Bosnian(code = "bs", language = "bosanski"),
//    Breton(code = "br", language = "brezhoneg"),
//    Bulgarian(code = "bg", language = "български"),
//    Burmese(code = "my", language = "မြန်မာ"),
//    Cantonese(code = "yue", language = "粤语"),
//    Catalan(code = "ca", language = "català"),
//    Cebuano(code = "ceb", language = "Cebuano"),
//    CentralAtlasTamazight(code = "tzm", language = "Tamaziɣt n laṭlaṣ"),
//    CentralKurdish(code = "ckb", language = "کوردیی ناوەندی"),
//    Chakma(code = "ccp", language = "𑄌𑄋𑄴𑄟𑄳𑄦"),
//    Chechen(code = "ce", language = "нохчийн"),
//    Cherokee(code = "chr", language = "ᏣᎳᎩ"),
//    Chiga(code = "cgg", language = "Rukiga"),
//    Chinese(code = "zh", language = "中文"),
//    Chuvash(code = "cv", language = "чӑваш"),
//    Colognian(code = "ksh", language = "Kölsch"),
//    Cornish(code = "kw", language = "kernewek"),
//    Croatian(code = "hr", language = "hrvatski"),
//    Czech(code = "cs", language = "čeština"),
//    Danish(code = "da", language = "dansk"),
//    Dogri(code = "doi", language = "डोगरी"),
//    Duala(code = "dua", language = "duálá"),
//    Dutch(code = "nl", language = "Nederlands"),
//    Dzongkha(code = "dz", language = "རྫོང་ཁ"),
//    Embu(code = "ebu", language = "Kĩembu"),
//    Esperanto(code = "eo", language = "esperanto"),
//    Estonian(code = "et", language = "eesti"),
//    Ewe(code = "ee", language = "Eʋegbe"),
//    Ewondo(code = "ewo", language = "ewondo"),
//    Faroese(code = "fo", language = "føroyskt"),
//    Filipino(code = "fil", language = "Filipino"),
//    Finnish(code = "fi", language = "suomi"),
//    French(code = "fr", language = "français"),
//    Friulian(code = "fur", language = "furlan"),
//    Fula(code = "ff", language = "𞤆𞤵𞤤𞤢𞤪"),
//    Galician(code = "gl", language = "galego"),
//    Ganda(code = "lg", language = "Luganda"),
//    Georgian(code = "ka", language = "ქართული"),
//    German(code = "de", language = "Deutsch"),
//    Greek(code = "el", language = "Ελληνικά"),
//    Gujarati(code = "gu", language = "ગુજરાતી"),
//    Gusii(code = "guz", language = "Ekegusii"),
//    Haryanvi(code = "bgc", language = "हरियाणवी"),
//    Hausa(code = "ha", language = "Hausa"),
//    Hawaiian(code = "haw", language = "ʻŌlelo Hawaiʻi"),
//    Hebrew(code = "he", language = "עברית"),
//    Hindi(code = "hi", language = "हिन्दी"),
//    Hungarian(code = "hu", language = "magyar"),
//    Icelandic(code = "is", language = "íslenska"),
//    Igbo(code = "ig", language = "Igbo"),
//    InariSami(code = "smn", language = "anarâškielâ"),
//    Indonesian(code = "id", language = "Indonesia"),
//    Interlingua(code = "ia", language = "interlingua"),
//    Irish(code = "ga", language = "Gaeilge"),
//    Italian(code = "it", language = "italiano"),
//    Japanese(code = "ja", language = "日本語"),
//    Javanese(code = "jv", language = "Jawa"),
//    JolaFonyi(code = "dyo", language = "joola"),
//    Kabuverdianu(code = "kea", language = "kabuverdianu"),
//    Kabyle(code = "kab", language = "Taqbaylit"),
//    Kaingang(code = "kgp", language = "kanhgág"),
//    Kako(code = "kkj", language = "kakɔ"),
//    Kalaallisut(code = "kl", language = "kalaallisut"),
//    Kalenjin(code = "kln", language = "Kalenjin"),
//    Kamba(code = "kam", language = "Kikamba"),
//    Kannada(code = "kn", language = "ಕನ್ನಡ"),
//    Kashmiri(code = "ks", language = "کٲشُر"),
//    Kazakh(code = "kk", language = "қазақ тілі"),
//    Khmer(code = "km", language = "ខ្មែរ"),
//    Kikuyu(code = "ki", language = "Gikuyu"),
//    Kinyarwanda(code = "rw", language = "Kinyarwanda"),
//    Konkani(code = "kok", language = "कोंकणी"),
//    Korean(code = "ko", language = "한국어"),
//    KoyraChiini(code = "khq", language = "Koyra ciini"),
//    KoyraboroSenni(code = "ses", language = "Koyraboro senni"),
//    Kurdish(code = "ku", language = "kurdî"),
//    Kwasio(code = "nmg", language = "nmg"),
//    Kyrgyz(code = "ky", language = "кыргызча"),
//    Lakota(code = "lkt", language = "Lakȟólʼiyapi"),
//    Langi(code = "lag", language = "Kɨlaangi"),
//    Lao(code = "lo", language = "ລາວ"),
//    Latvian(code = "lv", language = "latviešu"),
//    Lingala(code = "ln", language = "lingála"),
//    Lithuanian(code = "lt", language = "lietuvių"),
//    LowGerman(code = "nds", language = "Low German"),
//    LowerSorbian(code = "dsb", language = "dolnoserbšćina"),
//    LubaKatanga(code = "lu", language = "Tshiluba"),
//    Luo(code = "luo", language = "Dholuo"),
//    Luxembourgish(code = "lb", language = "Lëtzebuergesch"),
//    Luyia(code = "luy", language = "Luluhia"),
//    Macedonian(code = "mk", language = "македонски"),
//    Machame(code = "jmc", language = "Kimachame"),
//    Maithili(code = "mai", language = "मैथिली"),
//    MakhuwaMeetto(code = "mgh", language = "Makua"),
//    Makonde(code = "kde", language = "Chimakonde"),
//    Malagasy(code = "mg", language = "Malagasy"),
//    Malay(code = "ms", language = "Melayu"),
//    Malayalam(code = "ml", language = "മലയാളം"),
//    Maltese(code = "mt", language = "Malti"),
//    Manipuri(code = "mni", language = "মৈতৈলোন্"),
//    Manx(code = "gv", language = "Gaelg"),
//    Marathi(code = "mr", language = "मराठी"),
//    Masai(code = "mas", language = "Maa"),
//    Mazanderani(code = "mzn", language = "مازرونی"),
//    Meru(code = "mer", language = "Kĩmĩrũ"),
//    Meta(code = "mgo", language = "metaʼ"),
//    Moksha(code = "mdf", language = "мокшень кяль"),
//    Mongolian(code = "mn", language = "монгол"),
//    Morisyen(code = "mfe", language = "kreol morisien"),
//    Mundang(code = "mua", language = "MUNDAŊ"),
//    Maori(code = "mi", language = "Māori"),
//    Nama(code = "naq", language = "Khoekhoegowab"),
//    Nepali(code = "ne", language = "नेपाली"),
//    Ngiemboon(code = "nnh", language = "Shwóŋò ngiembɔɔn"),
//    Ngomba(code = "jgo", language = "Ndaꞌa"),
//    Nheengatu(code = "yrl", language = "nheẽgatu"),
//    NigerianPidgin(code = "pcm", language = "Naijíriá Píjin"),
//    NorthNdebele(code = "nd", language = "isiNdebele"),
//    NorthernFrisian(code = "frr", language = "Nordfriisk"),
//    NorthernLuri(code = "lrc", language = "لۊری شومالی"),
//    NorthernSami(code = "se", language = "davvisámegiella"),
//    Norwegian(code = "no", language = "norsk"),
//    NorwegianBokmal(code = "nb", language = "norsk bokmål"),
//    NorwegianNynorsk(code = "nn", language = "norsk nynorsk"),
//    Nuer(code = "nus", language = "Thok Nath"),
//    Nyankole(code = "nyn", language = "Runyankore"),
//    Obolo(code = "ann", language = "Obolo"),
//    Occitan(code = "oc", language = "Occitan"),
//    Odia(code = "or", language = "ଓଡ଼ିଆ"),
//    Oromo(code = "om", language = "Oromoo"),
//    Ossetic(code = "os", language = "ирон"),
//    Pashto(code = "ps", language = "پښتو"),
//    Persian(code = "fa", language = "فارسی"),
//    Pijin(code = "pis", language = "Pijin"),
//    Polish(code = "pl", language = "polski"),
//    Portuguese(code = "pt", language = "português"),
//    Punjabi(code = "pa", language = "ਪੰਜਾਬੀ"),
//    Quechua(code = "qu", language = "Runasimi"),
//    Rajasthani(code = "raj", language = "राजस्थानी"),
//    Romanian(code = "ro", language = "română"),
//    Romansh(code = "rm", language = "rumantsch"),
//    Rombo(code = "rof", language = "Kihorombo"),
//    Rundi(code = "rn", language = "Ikirundi"),
//    Russian(code = "ru", language = "русский"),
//    Rwa(code = "rwk", language = "Kiruwa"),
//    Samburu(code = "saq", language = "Kisampur"),
//    Sango(code = "sg", language = "Sängö"),
//    Sangu(code = "sbp", language = "Ishisangu"),
//    Sanskrit(code = "sa", language = "संस्कृत भाषा"),
//    Santali(code = "sat", language = "ᱥᱟᱱᱛᱟᱲᱤ"),
//    Sardinian(code = "sc", language = "sardu"),
//    ScottishGaelic(code = "gd", language = "Gàidhlig"),
//    Sena(code = "seh", language = "sena"),
//    Serbian(code = "sr", language = "српски"),
//    Shambala(code = "ksb", language = "Kishambaa"),
//    Shona(code = "sn", language = "chiShona"),
//    SichuanYi(code = "ii", language = "ꆈꌠꉙ"),
//    Sindhi(code = "sd", language = "سنڌي"),
//    Sinhala(code = "si", language = "සිංහල"),
//    SkoltSami(code = "sms", language = "sääʹmǩiõll"),
//    Slovak(code = "sk", language = "slovenčina"),
//    Slovenian(code = "sl", language = "slovenščina"),
//    Soga(code = "xog", language = "Olusoga"),
//    Somali(code = "so", language = "Soomaali"),
//    Spanish(code = "es", language = "español"),
//    StandardMoroccanTamazight(code = "zgh", language = "ⵜⴰⵎⴰⵣⵉⵖⵜ"),
//    Sundanese(code = "su", language = "Basa Sunda"),
//    Swahili(code = "sw", language = "Kiswahili"),
//    Swedish(code = "sv", language = "svenska"),
//    SwissGerman(code = "gsw", language = "Schwiizertüütsch"),
//    Tachelhit(code = "shi", language = "ⵜⴰⵛⵍⵃⵉⵜ"),
//    Taita(code = "dav", language = "Kitaita"),
//    Tajik(code = "tg", language = "тоҷикӣ"),
//    Tasawaq(code = "twq", language = "Tasawaq senni"),
//    Tatar(code = "tt", language = "татар"),
//    Telugu(code = "te", language = "తెలుగు"),
//    Teso(code = "teo", language = "Kiteso"),
//    Thai(code = "th", language = "ไทย"),
//    Tibetan(code = "bo", language = "བོད་སྐད་"),
//    Tigrinya(code = "ti", language = "ትግርኛ"),
//    TokiPona(code = "tok", language = "Toki Pona"),
//    Tongan(code = "to", language = "lea fakatonga"),
//    Turkish(code = "tr", language = "Türkçe"),
//    Turkmen(code = "tk", language = "türkmen dili"),
//    Ukrainian(code = "uk", language = "українська"),
//    UpperSorbian(code = "hsb", language = "hornjoserbšćina"),
//    Urdu(code = "ur", language = "اردو"),
//    Uyghur(code = "ug", language = "ئۇيغۇرچە"),
//    Uzbek(code = "uz", language = "o‘zbek"),
//    Vai(code = "vai", language = "ꕙꔤ"),
//    Vietnamese(code = "vi", language = "Tiếng Việt"),
//    Vunjo(code = "vun", language = "Kyivunjo"),
//    Walser(code = "wae", language = "Walser"),
//    Welsh(code = "cy", language = "Cymraeg"),
//    WesternFrisian(code = "fy", language = "Frysk"),
//    Wolof(code = "wo", language = "Wolof"),
//    Xhosa(code = "xh", language = "IsiXhosa"),
//    Yakut(code = "sah", language = "саха тыла"),
//    Yangben(code = "yav", language = "nuasue"),
//    Yiddish(code = "yi", language = "ייִדיש"),
//    Yoruba(code = "yo", language = "Èdè Yorùbá"),
//    Zarma(code = "dje", language = "Zarmaciine"),
//    Zulu(code = "zu", language = "isiZulu")
    ;

    companion object {

        fun find(name: String): AppLanguage {

            return try {

                valueOf(value = name)
            } catch (exception: Exception) {

                System
            }
        }
    }
}